Repository projectdiscovery/katana, pull requests merged in 2023-08, with the labels that each got.

#532 Patch: Add the Stored Response Path as Key in JSON Output
  pkg/navigation/response.go
  pkg/output/output.go
  pkg/output/responses.go
Labels: Type: Maintenance

#538 add resume option
  cmd/katana/main.go
  internal/runner/executer.go
  internal/runner/runner.go
  pkg/types/options.go
Labels: Type: Enhancement

#564 Fix headless options parsing issue
  internal/runner/options.go
  pkg/types/options.go
  pkg/types/options_test.go
Labels: Type: Bug
