Repository projectdiscovery/katana, pull requests merged in 2023-07, with the labels that each got.

#489 Add random tls impersonate
  cmd/katana/main.go
  pkg/engine/common/base.go
  pkg/engine/common/http.go
  pkg/types/options.go
Labels: Type: Enhancement

#492 feature: added jsluice based javascript parsing to default
  README.md
  cmd/katana/main.go
  go.mod
  go.sum
  pkg/engine/parser/parser.go
  pkg/types/options.go
  pkg/utils/jsluice.go
  pkg/utils/jsluice_test.go
Labels: Status: Review Needed

#537 Add DSL expression based matcher and filter flags
  .github/workflows/build-test.yml
  .github/workflows/functional-test.yml
  .github/workflows/lint-test.yml
  .github/workflows/release-binary.yml
  .github/workflows/security-crawl-maze-score.yaml
  README.md
  cmd/integration-test/filters.go
  cmd/integration-test/integration-test.go
  cmd/katana/main.go
  go.mod
  go.sum
  pkg/engine/parser/parser_test.go
  pkg/output/options.go
  pkg/output/output.go
  pkg/types/crawler_options.go
  pkg/types/options.go
Labels: Type: Enhancement

#527 Disabling cgo due to tree-sitter bindings
  .github/workflows/release-binary.yml
  .github/workflows/release-test.yml
  .gitignore
  .goreleaser.yml
  .goreleaser/linux.yml
  .goreleaser/mac.yml
  .goreleaser/windows.yml
Labels: Type: Bug
