Repository projectdiscovery/katana, pull requests merged in 2023-03, with the labels that each got.

#340 Add resolver in katana
  .github/workflows/lint-test.yml
  cmd/katana/main.go
  pkg/types/crawler_options.go
  pkg/types/options.go
Labels: Status: Review Needed

#312 Core Refactor
  README.md
  cmd/integration-test/library.go
  cmd/katana/main.go
  internal/runner/options.go
  internal/runner/runner.go
  pkg/engine/common/http.go
  pkg/engine/hybrid/crawl.go
  pkg/engine/hybrid/hybrid.go
  pkg/engine/parser/files/request.go
  pkg/engine/parser/files/robotstxt.go
  pkg/engine/parser/files/robotstxt_test.go
  pkg/engine/parser/files/sitemapxml.go
  pkg/engine/parser/files/sitemapxml_test.go
  pkg/engine/parser/parser.go
  pkg/engine/parser/parser_test.go
  pkg/engine/standard/crawl.go
  pkg/engine/standard/standard.go
  pkg/navigation/request.go
  pkg/navigation/response.go
  pkg/output/fields.go
  pkg/output/fields_test.go
  pkg/output/format_json.go
  pkg/output/format_screen.go
  pkg/output/output.go
  pkg/output/responses.go
  pkg/output/responses_test.go
  pkg/output/result.go
  pkg/types/crawler_options.go
  pkg/utils/extensions/extensions.go
  pkg/utils/queue/queue.go
  pkg/utils/queue/stragegy.go
  pkg/utils/utils.go
Labels: Type: Enhancement

#362 Fix katana consuming all cpu
  pkg/utils/queue/queue.go
Labels: Status: Review Needed

#373 Transparent embedding of common code
  go.mod
  go.sum
  pkg/engine/common/base.go
  pkg/engine/hybrid/crawl.go
  pkg/engine/hybrid/hybrid.go
  pkg/engine/parser/files/request.go
  pkg/engine/parser/files/robotstxt.go
  pkg/engine/parser/files/sitemapxml.go
  pkg/engine/parser/parser.go
  pkg/engine/parser/parser_test.go
  pkg/engine/standard/crawl.go
  pkg/engine/standard/standard.go
  pkg/navigation/request.go
  pkg/output/custom_field.go
  pkg/output/fields_test.go
  pkg/output/result.go
Labels: Type: Maintenance, Type: Optimization

#387 Fixing "do" functionality
  pkg/engine/common/base.go
  pkg/engine/common/error.go
Labels: Type: Bug
